version: "2"

services:
  credentials:
    # We need to run something, but running Django leads to Error 137 (out of memory).
    command: tail -f /dev/null
    environment:
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=memcached:11211
      - CONN_MAX_AGE=60
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=db
      - DB_NAME=credentials
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_USER=root
      - DJANGO_SETTINGS_MODULE=credentials.settings.test
      - ENABLE_DJANGO_TOOLBAR=1
    volumes:
      - .:/edx/app/credentials/credentials
